Pow=0;
Scale=0;
Dat='SCZ';
nG=5;

[G0,ID,Ax]=FCG_Load(Dat,[],1:nG);
Ax={[-8,8],[-8,8]};
nSubj=size(G0,3);
nG=size(G0,2);

G=FCG_Reg1(G0,1);
Gm=mean(G,3);

FCG_PrintGrads(G0(:,1:2,:), sprintf('%s_nS%d_nG%d_Reg0none_P%d_S%d_1v2',Dat,nSubj,nG,0,0),ID,Ax,...
              sprintf('%s Reg0none %d Subj  %d Grad',Dat,nSubj,nG,0,0))
FCG_PrintGrads(G0(:,[1,3],:), sprintf('%s_nS%d_nG%d_Reg0none_P%d_S%d_1v3',Dat,nSubj,nG,0,0),ID,Ax,...
              sprintf('%s Reg0none %d Subj  %d Grad',Dat,nSubj,nG,0,0))
FCG_PlotMatrix(mean(G0,3),'No Reg',Ax)
FCG_Print(sprintf('%s Reg0none %d Subj  %d Grad',    Dat,nSubj,nG,0,0),...
                           sprintf('%s_nS%d_nG%d_Reg0none_P%d_S%d',    Dat,nSubj,nG,0,0),'h')

FCG_PrintGrads(G(:,1:2,:), sprintf('%s_nS%d_nG%d_Reg0first_P%d_S%d_1v2',Dat,nSubj,nG,0,0),ID,Ax,...
              sprintf('%s Reg0first %d Subj  %d Grad',Dat,nSubj,nG,0,0))
FCG_PrintGrads(G(:,[1,3],:), sprintf('%s_nS%d_nG%d_Reg0first_P%d_S%d_1v3',Dat,nSubj,nG,0,0),ID,Ax,...
              sprintf('%s Reg0first %d Subj  %d Grad',Dat,nSubj,nG,0,0))
FCG_PlotMatrix(mean(G,3),'To First',Ax)
FCG_Print(sprintf('%s Reg0first %d Subj  %d Grad',    Dat,nSubj,nG,0,0),...
                           sprintf('%s_nS%d_nG%d_Reg0first_P%d_S%d',    Dat,nSubj,nG,0,0),'h')

R1=FCG_OrthProcReg(G,Gm); 
G1=FCG_ApplyReg(G,R1);
FCG_PrintGrads(G1(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg1mn1s_P%d_S%d_1v2',Dat,nSubj,nG,0,0),ID,Ax,...
               sprintf('%s Reg1-1stmean %d Subj  %d Grad',Dat,nSubj,nG,0,0))
FCG_PrintGrads(G1(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg1mn1s_P%d_S%d_1v3',Dat,nSubj,nG,0,0),ID,Ax,...
               sprintf('%s Reg1-1stmean %d Subj  %d Grad',Dat,nSubj,nG,0,0))
FCG_PlotMatrix(mean(G1,3),'To First Mean',Ax)
FCG_Print(sprintf('%s Reg1-1stmean %d Subj  %d Grad',    Dat,nSubj,nG,0,0),...
                           sprintf('%s_nS%d_nG%d_Reg1mn1s_P%d_S%d',    Dat,nSubj,nG,0,0),'h')

[G2,iRef2,R2,S2]=FCG_RegAll(G,0,0); 
FCG_PrintGrads(G2(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg2best_P%d_S%d_1v2',Dat,nSubj,nG,0,0),ID,Ax,...
    sprintf('%s Reg2best(%d) %d Subj  %d Grad',Dat,iRef2,nSubj,nG,0,0))
FCG_PrintGrads(G2(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg2best_P%d_S%d_1v3',Dat,nSubj,nG,0,0),ID,Ax,...
    sprintf('%s Reg2best(%d) %d Subj  %d Grad',Dat,iRef2,nSubj,nG,0,0))
FCG_PlotMatrix(mean(G2,3).*FCG_ScaleReg(mean(G2,3),Gm),'Rigid To Best',Ax)
FCG_Print(sprintf('%s Reg2best %d Subj  %d Grad',    Dat,nSubj,nG,0,0),...
                           sprintf('%s_nS%d_nG%d_Reg2best_P%d_S%d',    Dat,nSubj,nG,0,0),'h')

G20=FCG_RegAll(G0,0,0,iRef2);
FCG_PlotMatrix(mean(G2,3),'Rigid To Best (no align to 1st)',Ax)
FCG_Print(sprintf('%s Reg2best %d Subj  %d Grad',    Dat,nSubj,nG,0,0),...
                           sprintf('%s_nS%d_nG%d_Reg2bestNativ_P%d_S%d',    Dat,nSubj,nG,0,0),'h')

[G3,iRef3,R3,S3]=FCG_RegAll(G,0,1);
FCG_PrintGrads(G3(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg3best_P%d_S%d_1v2',Dat,nSubj,nG,0,1),ID,Ax,...
    sprintf('%s Reg3best(%d) %d Subj  %d Grad  Scaled',Dat,iRef3,nSubj,nG,0,1))
FCG_PrintGrads(G3(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg3best_P%d_S%d_1v3',Dat,nSubj,nG,0,1),ID,Ax,...
    sprintf('%s Reg3best(%d) %d Subj  %d Grad  Scaled',Dat,iRef3,nSubj,nG,0,1))
FCG_PlotMatrix(mean(G3,3).*FCG_ScaleReg(mean(G3,3),Gm),'Scaled To Best',Ax)
FCG_Print(sprintf('%s Reg3best %d Subj  %d Grad  Scaled',    Dat,nSubj,nG,0,1),...
                           sprintf('%s_nS%d_nG%d_Reg3best_P%d_S%d',    Dat,nSubj,nG,0,1),'h')

[G4,iRef4,R4,S4]=FCG_RegAll(G,0,-1);
FCG_PrintGrads(G4(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg4best_P%d_S%d_1v2',Dat,nSubj,nG,0,-1),ID,Ax,...
    sprintf('%s Reg4best(%d) %d Subj  %d Grad  Affine',Dat,iRef4,nSubj,nG,0,-1))
FCG_PrintGrads(G4(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg4best_P%d_S%d_1v3',Dat,nSubj,nG,0,-1),ID,Ax,...
    sprintf('%s Reg4best(%d) %d Subj  %d Grad  Affine',Dat,iRef4,nSubj,nG,0,-1))
FCG_PlotMatrix(mean(G4,3).*FCG_ScaleReg(mean(G4,3),Gm),'Affine To Best',Ax)
FCG_Print(sprintf('%s Reg4best %d Subj  %d Grad  Affine',    Dat,nSubj,nG,0,-1),...
                           sprintf('%s_nS%d_nG%d_Reg4best_P%d_S%d',    Dat,nSubj,nG,0,-1),'h')

[G5,iRef5,R5,S5]=FCG_RegAll(G,4,0);
FCG_PrintGrads(G5(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg5best_P%d_S%d_1v2',Dat,nSubj,nG,4,0),ID,Ax,...
    sprintf('%s Reg5best(%d) %d Subj  %d Grad  %d Pow',Dat,iRef5,nSubj,nG,4,0))
FCG_PrintGrads(G5(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg5best_P%d_S%d_1v3',Dat,nSubj,nG,4,0),ID,Ax,...
    sprintf('%s Reg5best(%d) %d Subj  %d Grad  %d Pow',Dat,iRef5,nSubj,nG,4,0))
FCG_PlotMatrix(mean(G5,3).*FCG_ScaleReg(mean(G5,3),Gm),'PowerWtd To Best',Ax)
FCG_Print(sprintf('%s Reg5best %d Subj  %d Grad  %d Pow',    Dat,nSubj,nG,4,0),...
                           sprintf('%s_nS%d_nG%d_Reg5best_P%d_S%d',    Dat,nSubj,nG,4,0),'h')

[G6,iRef6,R6,S6]=FCG_RegAll(G,4,1);
FCG_PrintGrads(G6(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg6best_P%d_S%d_1v2',Dat,nSubj,nG,4,1),ID,Ax,...
    sprintf('%s Reg6best(%d) %d Subj  %d Grad  %d Pow  Scaled',Dat,iRef6,nSubj,nG,4,1))
FCG_PrintGrads(G6(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg6best_P%d_S%d_1v3',Dat,nSubj,nG,4,1),ID,Ax,...
    sprintf('%s Reg6best(%d) %d Subj  %d Grad  %d Pow  Scaled',Dat,iRef6,nSubj,nG,4,1))
FCG_PlotMatrix(mean(G6,3).*FCG_ScaleReg(mean(G6,3),Gm),'PowerWtd+Scaled To Best',Ax)
FCG_Print(sprintf('%s Reg6best %d Subj  %d Grad  %d Pow  Scaled',    Dat,nSubj,nG,4,1),...
                           sprintf('%s_nS%d_nG%d_Reg6best_P%d_S%d',    Dat,nSubj,nG,4,1),'h')

[G7,iRef7,R7,S7]=FCG_RegAll(G,4,-1);
FCG_PrintGrads(G7(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg7best_P%d_S%d_1v2',Dat,nSubj,nG,4,-1),ID,Ax,...
    sprintf('%s Reg7best(%d) %d Subj  %d Grad  %d Pow  Affine',Dat,iRef7,nSubj,nG,4,-1))
FCG_PrintGrads(G7(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg7best_P%d_S%d_1v3',Dat,nSubj,nG,4,-1),ID,Ax,...
    sprintf('%s Reg7best(%d) %d Subj  %d Grad  %d Pow  Affine',Dat,iRef7,nSubj,nG,4,-1))
FCG_PlotMatrix(mean(G7,3).*FCG_ScaleReg(mean(G7,3),Gm),'PowerWtd+Affine To Best',Ax)
FCG_Print(sprintf('%s Reg7best %d Subj  %d Grad  %d Pow  Affine',    Dat,nSubj,nG,4,-1),...
                           sprintf('%s_nS%d_nG%d_Reg7best_P%d_S%d',    Dat,nSubj,nG,4,-1),'h')

[G3a,~,R3a,S3a]=FCG_RegAll(G,0,1,iRef2);
FCG_PrintGrads(G3a(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg3bestR_P%d_S%d_1v2',Dat,nSubj,nG,0,1),ID,Ax,...
    sprintf('%s Reg3bestR(%d) %d Subj  %d Grad  Scaled',Dat,iRef2,nSubj,nG,0,1))
FCG_PrintGrads(G3a(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg3bestR_P%d_S%d_1v3',Dat,nSubj,nG,0,1),ID,Ax,...
    sprintf('%s Reg3bestR(%d) %d Subj  %d Grad  Scaled',Dat,iRef2,nSubj,nG,0,1))
FCG_PlotMatrix(mean(G3a,3).*FCG_ScaleReg(mean(G3a,3),Gm),'Scaled To Rigid Best',Ax)
FCG_Print(sprintf('%s Reg3bestR %d Subj  %d Grad  Scaled',    Dat,nSubj,nG,0,1),...
                           sprintf('%s_nS%d_nG%d_Reg3bestR_P%d_S%d',    Dat,nSubj,nG,0,1),'h')

[G4a,~,R4a,S4a]=FCG_RegAll(G,0,-1,iRef2);
FCG_PrintGrads(G4a(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg4bestR_P%d_S%d_1v2',Dat,nSubj,nG,0,-1),ID,Ax,...
    sprintf('%s Reg4bestR(%d) %d Subj  %d Grad  Affine',Dat,iRef2,nSubj,nG,0,-1))
FCG_PrintGrads(G4a(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg4bestR_P%d_S%d_1v3',Dat,nSubj,nG,0,-1),ID,Ax,...
    sprintf('%s Reg4bestR(%d) %d Subj  %d Grad  Affine',Dat,iRef2,nSubj,nG,0,-1))
FCG_PlotMatrix(mean(G4a,3).*FCG_ScaleReg(mean(G4a,3),Gm),'Affine To Rigid Best',Ax)
FCG_Print(sprintf('%s Reg4bestR %d Subj  %d Grad  Affine',    Dat,nSubj,nG,0,-1),...
                           sprintf('%s_nS%d_nG%d_Reg4bestR_P%d_S%d',    Dat,nSubj,nG,0,-1),'h')

[G5a,~,R5a,S5a]=FCG_RegAll(G,4,0,iRef2);
FCG_PrintGrads(G5a(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg5bestR_P%d_S%d_1v2',Dat,nSubj,nG,4,0),ID,Ax,...
    sprintf('%s Reg5bestR(%d) %d Subj  %d Grad  %d Pow',Dat,iRef2,nSubj,nG,4,0))
FCG_PrintGrads(G5a(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg5bestR_P%d_S%d_1v3',Dat,nSubj,nG,4,0),ID,Ax,...
    sprintf('%s Reg5bestR(%d) %d Subj  %d Grad  %d Pow',Dat,iRef2,nSubj,nG,4,0))
FCG_PlotMatrix(mean(G5a,3).*FCG_ScaleReg(mean(G5a,3),Gm),'PowerWtd To Rigid Best',Ax)
FCG_Print(sprintf('%s Reg5bestR %d Subj  %d Grad  %d Pow',    Dat,nSubj,nG,4,0),...
                           sprintf('%s_nS%d_nG%d_Reg5bestR_P%d_S%d',    Dat,nSubj,nG,4,0),'h')

[G6a,~,R6a,S6a]=FCG_RegAll(G,4,1,iRef2);
FCG_PrintGrads(G6a(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg6bestR_P%d_S%d_1v2',Dat,nSubj,nG,4,1),ID,Ax,...
    sprintf('%s Reg6bestR(%d) %d Subj  %d Grad  %d Pow  Scaled',Dat,iRef2,nSubj,nG,4,1))
FCG_PrintGrads(G6a(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg6bestR_P%d_S%d_1v3',Dat,nSubj,nG,4,1),ID,Ax,...
    sprintf('%s Reg6bestR(%d) %d Subj  %d Grad  %d Pow  Scaled',Dat,iRef2,nSubj,nG,4,1))
FCG_PlotMatrix(mean(G6a,3).*FCG_ScaleReg(mean(G6a,3),Gm),'PowerWtd+Scaled To Rigid Best',Ax)
FCG_Print(sprintf('%s Reg6bestR %d Subj  %d Grad  %d Pow  Scaled',    Dat,nSubj,nG,4,1),...
                           sprintf('%s_nS%d_nG%d_Reg6bestR_P%d_S%d',    Dat,nSubj,nG,4,1),'h')

[G7a,~,R7a,S7a]=FCG_RegAll(G,4,-1,iRef2);
FCG_PrintGrads(G7a(:,1:2,:),sprintf('%s_nS%d_nG%d_Reg7bestR_P%d_S%d_1v2',Dat,nSubj,nG,4,-1),ID,Ax,...
    sprintf('%s Reg7bestR(%d) %d Subj  %d Grad  %d Pow  Affine',Dat,iRef2,nSubj,nG,4,-1))
FCG_PrintGrads(G7a(:,[1,3],:),sprintf('%s_nS%d_nG%d_Reg7bestR_P%d_S%d_1v3',Dat,nSubj,nG,4,-1),ID,Ax,...
    sprintf('%s Reg7bestR(%d) %d Subj  %d Grad  %d Pow  Affine',Dat,iRef2,nSubj,nG,4,-1))
FCG_PlotMatrix(mean(G7a,3).*FCG_ScaleReg(mean(G7a,3),Gm),'PowerWtd+Affine To Rigid Best',Ax)
FCG_Print(sprintf('%s Reg7bestR %d Subj  %d Grad  %d Pow  Affine',    Dat,nSubj,nG,4,-1),...
                           sprintf('%s_nS%d_nG%d_Reg7bestR_P%d_S%d',    Dat,nSubj,nG,4,-1),'h')
