function FCG_Print(Titl,PDFnm,Orient)
    axes('position',[0 0 1 1],'visible','off');
    if (Orient=='h')
        fullpage('h')
        axes('position',[0 0 1 1],'visible','off');
        text(0.05,0.5,...
             sprintf(Titl),...
                     'rotation',90,...
                     'fontsize',20,...
                     'horizontalalign','center',...
                     'verticalalign','middle')
    else
        fullpage(Orient)
        text(0.5,0.96,...
             sprintf(Titl),...
                     'rotation',0,...
                     'fontsize',20,...
                     'horizontalalign','center',...
                     'verticalalign','top')
    end
    print('-dpdf','-vector',[PDFnm '.pdf'])
end

